# Generated by Django 4.2.11 on 2024-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="reminder_method",
            field=models.CharField(
                blank=True,
                choices=[("SMS", "SMS"), ("Email", "Email")],
                max_length=10,
                null=True,
            ),
        ),
    ]
